### check adding blog into blogs table with authorization token header to add new blogs works  
### the string bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkhlbWFudGhAZW1haWwuY29tIiwiaWQiOjEsImlhdCI6MTY2ODQwNTYwMX0.fpPb17KImNaIx7J9QOmKbaJmPo9voi3fqVyy6xMZyuA, where the second value is the token returned by the login operation.
POST http://localhost:3001/api/blogs HTTP/1.1
Content-Type: application/json
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkhlbWFudGhAZW1haWwuY29tIiwiaWQiOjEsImlhdCI6MTY2ODQwNTYwMX0.fpPb17KImNaIx7J9QOmKbaJmPo9voi3fqVyy6xMZyuA

{
  "author": "George Lucas",
  "url": "https://www.starwars.com",
  "title": "May the Force be with you"
}


### check adding blog into blogs table with authorization token header to add new blogs fails cause of year vlaue not between 1991 to current year
### the string bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkhlbWFudGhAZW1haWwuY29tIiwiaWQiOjEsImlhdCI6MTY2ODQwNTYwMX0.fpPb17KImNaIx7J9QOmKbaJmPo9voi3fqVyy6xMZyuA, where the second value is the token returned by the login operation.
POST http://localhost:3001/api/blogs HTTP/1.1
Content-Type: application/json
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkhlbWFudGhAZW1haWwuY29tIiwiaWQiOjEsImlhdCI6MTY2ODQwNTYwMX0.fpPb17KImNaIx7J9QOmKbaJmPo9voi3fqVyy6xMZyuA

{
  "author": "Gene Roddenberry",
  "url": "https://intl.startrek.com/",
  "title": "Live long and prosper!",
  "year": 1990
}


### check adding blog into blogs table with authorization token header to add new blogs along with valid year value between 1991 to current year
### the string bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkhlbWFudGhAZW1haWwuY29tIiwiaWQiOjEsImlhdCI6MTY2ODQwNTYwMX0.fpPb17KImNaIx7J9QOmKbaJmPo9voi3fqVyy6xMZyuA, where the second value is the token returned by the login operation.
POST http://localhost:3001/api/blogs HTTP/1.1
Content-Type: application/json
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkhlbWFudGhAZW1haWwuY29tIiwiaWQiOjEsImlhdCI6MTY2ODQwNTYwMX0.fpPb17KImNaIx7J9QOmKbaJmPo9voi3fqVyy6xMZyuA

{
  "author": "Gene Roddenberry",
  "url": "https://intl.startrek.com/",
  "title": "Live long and prosper!",
  "year": 2007
}


### this blog is added by user mluukkai
### check adding blog into blogs table with authorization token header to add new blogs works  
### the string bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpQGVtYWlsLmNvbSIsImlkIjoyLCJpYXQiOjE2Njg0MDU2NzV9.AxAqROcRrzYA3-NtMx-3IzwtJ2mCWV0pewzzPVHYiMo, where the second value is the token returned by the login operation.
POST http://localhost:3001/api/blogs HTTP/1.1
Content-Type: application/json
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpQGVtYWlsLmNvbSIsImlkIjoyLCJpYXQiOjE2Njg0MDU2NzV9.AxAqROcRrzYA3-NtMx-3IzwtJ2mCWV0pewzzPVHYiMo

{
  "author": "Malcolm Wheeler-Nicholson",
  "url": "https://www.dc.com/",
  "title": "I'm Batman"
}